conditions = {
    "Sunny": "sunny.png",
    "Partly cloudy": "partly_cloudy.png",
    "Cloudy": "cloudy_ios.png",
    "Overcast": "",
    "Mist": "",
    "Patchy rain possible": "",
    "Patchy snow possible": "",
    "Patchy sleet possible": "",
    "Patchy freezing drizzle possible": "",
    "Thundery outbreaks possible": "",
    "Blowing snow": "snow.png",
    "Blizzard": "snow.png",
    "Fog": "",
    "Freezing fog": "",
    "Patchy light drizzle": "drizzle_nighttime.png",
    "Light drizzle": "",
    "Freezing drizzle": "",
    "Heavy freezing drizzle": "",
    "Patchy light rain": "",
    "Light rain": "",
    "Moderate rain at times": "",
    "Moderate rain": "",
    "Heavy rain at times": "",
    "Heavy rain": "rain.png",
    "Light freezing rain": "",
}
