conditions = {
    "Sunny": "sunny.png",
    "Partly cloudy": "partly_cloudy.png",
    "Cloudy": "cloudy_ios.png",
    "Overcast": "sunny.png",
    "Mist": "sunny.png",
    "Patchy rain possible": "sunny.png",
    "Patchy snow possible": "sunny.png",
    "Patchy sleet possible": "sunny.png",
    "Patchy freezing drizzle possible": "sunny.png",
    "Thundery outbreaks possible": "sunny.png",
    "Blowing snow": "snow.png",
    "Blizzard": "snow.png",
    "Fog": "sunny.png",
    "Freezing fog": "sunny.png",
    "Patchy light drizzle": "drizzle_nighttime.png",
    "Light drizzle": "sunny.png",
    "Freezing drizzle": "sunny.png",
    "Heavy freezing drizzle": "sunny.png",
    "Patchy light rain": "sunny.png",
    "Light rain": "sunny.png",
    "Moderate rain at times": "sunny.png",
    "Moderate rain": "sunny.png",
    "Heavy rain at times": "sunny.png",
    "Heavy rain": "rain.png",
    "Light freezing rain": "sunny.png",
    "Clear": "sunny.png",
}
